os: linux
language: node_js
node_js: '12'
branches:
  only:
  - master
  - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn test:unit
  - yarn build:lib
  - yarn check:size
  - yarn build:demo
after_script:
  - npm install -g codecov
  - codecov
deploy:
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  verbose: true
  on:
    branch: master
